"""Central, presentation-only localization helper for the Streamlit UI.

The UI uses stable keys rather than duplicating translated strings.  English is
the deliberate startup fallback; Turkish remains available through the UI.
"""

from __future__ import annotations

import json
from pathlib import Path
from functools import wraps

import streamlit as st


STRINGS = {
    "tr": {
        "analysis_settings": "Analiz ayarları",
        "new_analysis": "Yeni analiz",
        "start_analysis_short": "Analize başla →",
        "change_analysis": "Analizi değiştir",
        "workspace": "Çalışma alanı",
        "perturbation": "Pertürbasyon",
        "unified_and_records": "Unified ve kayıtlar",
        "organism": "Organizma",
        "human": "İnsan (Homo sapiens)",
        "mouse": "Fare (Mus musculus)",
        "human_protein_network": "İnsan protein ağı",
        "mouse_protein_network": "Fare protein ağı",
        "tissue": "Doku",
        "tissue_filter_active": "Doku filtresi etkin",
        "tissue_filter_off": "Doku filtresi kapalı",
        "calculation_engine_help": "Classic mevcut yönsüz motoru çalıştırır. Directed yönlü, Evidence ayrıştırılmış STRING kanıtlı hesabı ayrıca üretir. Compare Classic ve Directed sonucunu karşılaştırır.",
        "target": "Hedef",
        "target_type": "Hedef türü",
        "search_gene": "Gen Adı Ara",
        "select_disease": "Hastalık Seç",
        "manual_localization": "Manuel Lokalizasyon",
        "choose_options": "Seçenekleri seçin",
        "select_one_or_more_genes": "Bir veya daha fazla gen seçin",
        "target_count": "hedef",
        "tissue_expression_query": "Doku ifadesi sorgusu",
        "advanced_settings": "Gelişmiş ayarlar",
        "remaining_edge_weight": "Kalan kenar ağırlığı",
        "network_importance_spread": "Ağ önemi yayılımı (α)",
        "hill_coefficient": "Hill Katsayısı (n)",
        "paralog_boost": "Paralog Boost (%)",
        "betweenness_accuracy": "Betweenness hassasiyeti",
        "fast": "Hızlı",
        "balanced": "Dengeli",
        "full": "Tam",
        "max_network_nodes": "'Gerçek Ağ' görünümünde maks. düğüm",
        "max_network_labels": "'Gerçek Ağ' görünümünde maks. etiket",
        "restore_defaults": "Varsayılanları Yükle",
        "start_analysis": "Analizi Başlat",
        "target_tools": "Hedefe dolaylı etki ve telafi adayları",
        "effect_mode": "Etki modu",
        "network_mediated_effect": "Ağ-Aracılı Etki",
        "direct_effect": "Doğrudan Etki",
        "combined": "Birleşik",
        "candidate_limit": "Aday limiti",
        "system": "Sistem",
        "local_resource_usage": "Yerel kaynak kullanımı",
        "maintenance_tools": "Bakım ve teknik araçlar",
        "negative_candidate_count": "Gösterilecek negatif aday sayısı",
        "loss_view_settings": "Ağ önemi kaybı · görünüm ayarları",
        "language": "Dil",
        "analysis_summary": "Analiz özeti",
        "perturbation_target": "Pertürbasyon hedefi",
        "redistribution_candidate": "Yeniden dağılım adayı",
        "affected_records": "Etkilenen kayıt",
        "local_efficiency_change": "YEREL VERİMLİLİK DEĞİŞİMİ",
        "mean_local_efficiency_change": "ORTALAMA YEREL VERİMLİLİK DEĞİŞİMİ",
        "target_local_efficiency_change": "HEDEF-YEREL VERİMLİLİK DEĞİŞİMİ",
        "global_efficiency_change": "Global verimlilik değişimi",
        "network_redistribution": "AĞ YENİDEN DAĞILIMI",
        "perturbation_targets": "PERTÜRBASYON HEDEFLERİ",
        "targets_table_export": "Pertürbasyon hedefleri — tablo ve dışa aktarım",
        "number_genes_to_test": "Test edilecek gen sayısı",
        "gene_count_help": "Daha yüksek değerler daha geniş bir tarama yapar ancak analiz süresini artırır. 100 genlik tarama mevcut sistemde yaklaşık 5 dakika sürebilir.",
        "network_importance_loss": "Ağ Önemi Kaybı",
        "minimum_network_importance_loss": "Minimum ağ önemi kaybı (%)",
        "network_importance_change": "Ağ önemi değişimi (%)",
        "baseline_network_importance": "Başlangıç ağ önemi",
        "hinterland_score": "Ağdaki Önemi",
        "gateway": "Compartment Bottleneck",
        "evidence_details": "Kanıt ve teknik ayrıntılar",
        "when_to_use": "Ne zaman kullanılır?",
        "tissue_aware_protein_network_analysis": "DOKUYA DUYARLI PROTEİN AĞI ANALİZİ",
        "analysis_context_tissue": "Analiz bağlamı · doku",
        "analysis_context_target": "Analiz bağlamı · hedef",
        "target_gene_mode": "Hedef gen modu",
        "localization_mode": "Lokalizasyon modu",
        "all_proteome": "Tüm proteom",
        "edge_attenuation": "kenar zayıflatma",
        "calculation_engine": "Hesaplama motoru",
        "protein_network_perturbation": "Protein ağı pertürbasyonu",
        "network_visualization": "Ağ görselleştirmesi",
        "network_response": "AĞ YANITI",
        "research_context": "Araştırma bağlamı",
        "explore_research_context": "Araştırma bağlamını incele",
        "research_context_intro": "Araştırma bağlamı yereldir ve salt okunurdur. Varlık eşlemeleri ile yerel kanıt yalnızca istendiğinde yüklenir.",
        "explore_research_context_help": "Bu anlık görüntü için çevrimdışı Genel Bakış, Aileler, İşlevler ve İlişkiler görünümlerini oluşturur.",
        "preparing_research_context": "Yerel araştırma bağlamı hazırlanıyor…",
        "research_context_unavailable": "Araştırma bağlamı kullanılamıyor; simülasyon sonucu ve dışa aktarımlar değişmeden kalır.",
        "directed_calculation_engine": "Yönlü hesaplama motoru",
        "classic_vs_directed_comparison": "Classic ve Directed · Karşılaştırma",
        "statistical_validation_null_fdr_only": "İstatistiksel doğrulama yalnızca ampirik null + BH-FDR aday seçimi kullanıldığında gösterilir.",
        "statistical_validation_fields_unavailable": "Ampirik null + BH-FDR aday seçimi kullanıldı; ancak gösterilecek istatistik alanı yok.",
        "mouse_test": "Fare testi",
        "orthology_status_direct_ortholog_available": "Doğrudan bire-bir fare ortoloğu ve hesaplama bağlamı kullanılabilir",
        "orthology_status_ortholog_exists_not_in_graph": "Ortolog var, ancak fare ağında yok",
        "orthology_status_ortholog_exists_context_unavailable": "Ortolog var, ancak seçili fare bağlamında yok",
        "orthology_status_multiple_orthologs": "Birden çok ortolog: açık kullanıcı seçimi gerekli",
        "orthology_status_no_direct_ortholog": "Yetkili doğrudan fare ortoloğu yok",
        "orthology_status_functional_proxy_available": "İşlevsel vekil adayı mevcut",
        "orthology_status_no_defensible_proxy": "Savunulabilir işlevsel vekil yok",
        "orthology_status_unresolved": "Çözümlenemedi",
        "directed_relation_bidirectional": "Hedef ↔ bu kayıt",
        "directed_relation_target_to_entity": "Hedef → bu kayıt",
        "directed_relation_entity_to_target": "Bu kayıt → hedef",
        "directed_relation_no_direct_relation": "Hedefle doğrudan yönlü ilişki kaydı yok",
        "directed_support_omnipath": "OmniPath yön kaydı",
        "directed_support_undirected_fallback": "Yönsüz STRING ilişkisi kullanıldı",
        "directed_support_none": "Yön kaynağı kaydı yok",
        "directed_response_influence_gain": "Ağ önemi artışı",
        "directed_response_influence_loss": "Ağ önemi kaybı",
        "directed_response_no_change": "Değişim yok",
        "directed_response_perturbation_target": "Pertürbasyon hedefi",
        "directed_direction": "Yön",
        "directed_percent_change": "Yönlü % değişim",
        "classic_percent_change": "Classic % değişim",
        "difference": "Fark",
        "classic_rank": "Classic sırası",
        "directed_rank": "Directed sırası",
        "rank_shift": "Sıra değişimi",
        "directed_relation": "İlişki",
        "directed_support": "Yön kaynağı",
        "directed_coverage": "Yön kaynağı kapsamı",
        "directed_localization": "Lokalizasyon",
    },
    "en": {
        "analysis_settings": "Analysis settings",
        "new_analysis": "New analysis",
        "start_analysis_short": "Start analysis →",
        "change_analysis": "Change analysis",
        "workspace": "Workspace",
        "perturbation": "Perturbation",
        "unified_and_records": "Unified & records",
        "organism": "Organism",
        "human": "Human (Homo sapiens)",
        "mouse": "Mouse (Mus musculus)",
        "human_protein_network": "Human protein network",
        "mouse_protein_network": "Mouse protein network",
        "tissue": "Tissue",
        "tissue_filter_active": "Tissue filter active",
        "tissue_filter_off": "Tissue filter off",
        "calculation_engine_help": "Classic runs the current undirected engine. Directed separately produces directional results, Evidence uses separated STRING evidence, and Compare contrasts the Classic and Directed results.",
        "target": "Target",
        "target_type": "Target type",
        "search_gene": "Search gene name",
        "select_disease": "Select disease",
        "manual_localization": "Manual localization",
        "choose_options": "Choose options",
        "select_one_or_more_genes": "Select one or more genes",
        "target_count": "target(s)",
        "tissue_expression_query": "Tissue expression query",
        "advanced_settings": "Advanced settings",
        "remaining_edge_weight": "Remaining edge weight",
        "network_importance_spread": "Network-importance propagation (α)",
        "hill_coefficient": "Hill coefficient (n)",
        "paralog_boost": "Paralog boost (%)",
        "betweenness_accuracy": "Betweenness accuracy",
        "fast": "Fast",
        "balanced": "Balanced",
        "full": "Full",
        "max_network_nodes": "Maximum nodes in the Real Network view",
        "max_network_labels": "Maximum labels in the Real Network view",
        "restore_defaults": "Restore defaults",
        "start_analysis": "Start analysis",
        "target_tools": "Indirect target effects & compensation candidates",
        "effect_mode": "Effect mode",
        "network_mediated_effect": "Network-mediated effect",
        "direct_effect": "Direct effect",
        "combined": "Combined",
        "candidate_limit": "Candidate limit",
        "system": "System",
        "local_resource_usage": "Local resource usage",
        "maintenance_tools": "Maintenance & technical tools",
        "negative_candidate_count": "Number of negative candidates to show",
        "loss_view_settings": "Network-importance loss · display settings",
        "language": "Language",
        "analysis_summary": "Analysis summary",
        "perturbation_target": "Perturbation target",
        "redistribution_candidate": "Redistribution candidate",
        "affected_records": "Affected records",
        "local_efficiency_change": "LOCAL EFFICIENCY CHANGE",
        "mean_local_efficiency_change": "MEAN LOCAL EFFICIENCY CHANGE",
        "target_local_efficiency_change": "TARGET-LOCAL EFFICIENCY CHANGE",
        "global_efficiency_change": "Global efficiency change",
        "network_redistribution": "NETWORK REDISTRIBUTION",
        "perturbation_targets": "PERTURBATION TARGETS",
        "targets_table_export": "Perturbation targets — table & export",
        "number_genes_to_test": "Number of genes to test",
        "gene_count_help": "Higher values perform a broader search but increase analysis time. A 100-gene scan may take approximately 5 minutes on the current system.",
        "network_importance_loss": "Network Importance Loss",
        "minimum_network_importance_loss": "Minimum network importance loss (%)",
        "network_importance_change": "Network importance change (%)",
        "baseline_network_importance": "Baseline network importance",
        "hinterland_score": "Network Importance",
        "gateway": "Compartment Bottleneck",
        "evidence_details": "Evidence and technical details",
        "when_to_use": "When to use",
        "tissue_aware_protein_network_analysis": "TISSUE-AWARE PROTEIN NETWORK ANALYSIS",
        "analysis_context_tissue": "Analysis context · tissue",
        "analysis_context_target": "Analysis context · target",
        "target_gene_mode": "Target-gene mode",
        "localization_mode": "Localization mode",
        "all_proteome": "All proteome",
        "edge_attenuation": "edge attenuation",
        "calculation_engine": "Calculation Engine",
        "protein_network_perturbation": "Protein Network Perturbation",
        "network_visualization": "Network visualization",
        "network_response": "NETWORK RESPONSE",
        "research_context": "Research Context",
        "explore_research_context": "Explore Research Context",
        "research_context_intro": "Research Context is local and read-only. Entity maps and local evidence are loaded only when requested.",
        "explore_research_context_help": "Build the offline Overview, Families, Functions and Relationships views for this snapshot.",
        "preparing_research_context": "Preparing local Research Context…",
        "research_context_unavailable": "Research Context is unavailable; the simulation result and exports remain unchanged.",
        "directed_calculation_engine": "Directed Calculation Engine",
        "classic_vs_directed_comparison": "Classic vs Directed · Comparison",
        "statistical_validation_null_fdr_only": "Statistical validation is shown only when empirical-null + BH-FDR candidate selection is used.",
        "statistical_validation_fields_unavailable": "Empirical-null + BH-FDR candidate selection was used, but no statistical fields are available to display.",
        "mouse_test": "Mouse test",
        "orthology_status_direct_ortholog_available": "Direct one-to-one Mouse ortholog and calculation context are available",
        "orthology_status_ortholog_exists_not_in_graph": "Ortholog exists but is absent from the Mouse graph",
        "orthology_status_ortholog_exists_context_unavailable": "Ortholog exists but is unavailable in the selected Mouse context",
        "orthology_status_multiple_orthologs": "Multiple orthologs: an explicit user choice is required",
        "orthology_status_no_direct_ortholog": "No authoritative direct Mouse ortholog",
        "orthology_status_functional_proxy_available": "Functional proxy candidate available",
        "orthology_status_no_defensible_proxy": "No defensible functional proxy",
        "orthology_status_unresolved": "Unresolved",
        "directed_relation_bidirectional": "Target ↔ this record",
        "directed_relation_target_to_entity": "Target → this record",
        "directed_relation_entity_to_target": "This record → target",
        "directed_relation_no_direct_relation": "No direct directional relationship record with the target",
        "directed_support_omnipath": "OmniPath direction record",
        "directed_support_undirected_fallback": "Undirected STRING relationship used",
        "directed_support_none": "No direction-source record",
        "directed_response_influence_gain": "Network-importance gain",
        "directed_response_influence_loss": "Network-importance loss",
        "directed_response_no_change": "No change",
        "directed_response_perturbation_target": "Perturbation target",
        "directed_direction": "Direction",
        "directed_percent_change": "Directed % change",
        "classic_percent_change": "Classic % change",
        "difference": "Difference",
        "classic_rank": "Classic rank",
        "directed_rank": "Directed rank",
        "rank_shift": "Rank shift",
        "directed_relation": "Relation",
        "directed_support": "Direction source",
        "directed_coverage": "Direction-source coverage",
        "directed_localization": "Localization",
    },
}


def _load_locale_overrides() -> None:
    """Overlay editable locale resources without coupling them to analysis code."""
    locale_dir = Path(__file__).with_name("locales")
    for language in ("en", "tr"):
        path = locale_dir / f"{language}.json"
        try:
            with path.open(encoding="utf-8") as source:
                values = json.load(source)
            if isinstance(values, dict):
                STRINGS[language].update({str(key): str(value) for key, value in values.items()})
        except (OSError, json.JSONDecodeError):
            # The built-in dictionary keeps the interface usable if a resource is absent.
            continue


_load_locale_overrides()


# Existing screens contain legacy literal messages.  This presentation-only
# catalogue lets the central locale select the right wording while those
# messages are progressively moved to explicit keys.  It never touches data,
# calculations, widget values, or internal identifiers.
EN_REPLACEMENTS = {
    "Doku ifadesi sorgusu": "Tissue expression query",
    "Dokuları sorgula": "Query tissues",
    "Gelişmiş ayarlar": "Advanced settings",
    "Hedefe dolaylı etki ve telafi adayları": "Indirect target effects & compensation candidates",
    "Sistem": "System",
    "Yerel kaynak kullanımı": "Local resource usage",
    "Bakım ve teknik araçlar": "Maintenance & technical tools",
    "Analizi Başlat": "Start analysis",
    "Analizi şimdi çalıştır": "Run analysis now",
    "Çalışma alanını nasıl kullanırım?": "How do I use this workspace?",
    "Nasıl çalışır?": "How does it work?",
    "Mod seçimine dön": "Return to mode selection",
    "Ağ bağlamı": "Network context",
    "Ağ önemi kaybı · görünüm ayarları": "Network-importance loss · display settings",
    "Gösterilecek negatif aday sayısı": "Number of negative candidates to show",
    "Tablo boş.": "The table is empty.",
    "Tamamını İndir": "Download all",
    "CSV İndir": "Download CSV",
    "İndir": "Download",
    "satırdan ilk": "rows; showing the first",
    "satır": "rows",
    "Araştırma bağlamı hazırlanıyor": "Preparing Research Context",
    "Araştırma bağlamı hazırlanamadı; simülasyon sonucu değişmedi.": "Research Context could not be prepared; the simulation result is unchanged.",
    "Araştırma bağlamı görüntülenemedi; simülasyon sonucu değişmedi.": "Research Context could not be displayed; the simulation result is unchanged.",
    "Hastalık bağlamı kullanılamıyor; simülasyon sonucu değişmedi.": "Disease Context is unavailable; the simulation result is unchanged.",
    "Simülasyon çalışıyor": "Simulation running",
    "Simülasyon tamamlandı": "Simulation complete",
    "Simülasyon hatası": "Simulation error",
    "Simülasyon tamamlanamadı.": "Simulation could not be completed.",
    "Veri alınamadı.": "No data could be retrieved.",
    "Veri formatı beklenmeyen tipte.": "The data format has an unexpected type.",
    "Bellekten sonuç alınamadı, diskteki rapor deneniyor": "The result was unavailable in memory; trying the report on disk",
    "Doku filtresi etkin": "Tissue filter active",
    "Doku filtresi kapalı": "Tissue filter off",
    "İnsan protein ağı": "Human protein network",
    "Fare protein ağı": "Mouse protein network",
    "Fare modu": "Mouse mode",
    "İnsan": "Human",
    "Fare": "Mouse",
    "Hedef sayısı": "Target",
    "Hedef genler": "Target genes",
    "Seçilen hedef": "Selected target",
    "Simüle Edilen Hedef": "Simulated target",
    "Simülasyon Hedefi": "Simulation target",
    "Ağdaki Önemi": "Network Importance",
    "Ağ önemi değişimi (%)": "Network importance change (%)",
    "Ağ Önemi Kaybı": "Network Importance Loss",
    "Başlangıç ağ önemi": "Baseline network importance",
    "Pertürbasyon sonrası ağ önemi": "Post-perturbation network importance",
    "Geçiş Merkeziliği": "Betweenness centrality",
    "Topluluk kimliği": "Community identifier",
    "Sistemik ağ kayması (%)": "Systemic network shift (%)",
    "Ampirik p-değeri": "Empirical p-value",
    "q-değeri (FDR)": "q-value (FDR)",
    "İstatistiksel destek": "Statistical support",
    "Yaşamsallık (Essentiality)": "Essentiality",
    "İlaçlanabilirlik skoru": "Druggability score",
    "Bulgu sınıfı": "Finding class",
    "Yön duyarlılığı": "Direction sensitivity",
    "Yüzdelik farkı": "Percentile difference",
    "Aynı işaret": "Same sign",
    "İşaret değişimi": "Sign flip",
    "İşaret uyumu": "Sign agreement",
    "Deneysel destek": "Experimental support",
    "Veritabanı desteği": "Database support",
    "kullanılabilir": "available",
    "Kullanılamıyor": "Unavailable",
    "Hazır": "Ready",
    "Tamamlandı": "Complete",
    "Kısmi": "Partial",
    "Başarısız": "Failed",
    "Hücresel konum": "Cellular location",
    "Sonuç dizini": "Results index",
    "Ağ sonuçları": "Network results",
    "Aday sonuçları": "Candidate results",
    "Biyolojik sonuçlar": "Biological results",
    "İşaretli ağ yanıtı": "Signed network response",
    "Analiz bağlamı ve kullanılan parametreler": "Analysis context & parameters used",
    "Kalan kenar ağırlığı": "Remaining edge weight",
    "BC örnek kaynak sayısı": "BC sample-source count",
    "Yeniden-dağılım aday sınırı": "Redistribution candidate limit",
    "Ağ görünümü düğüm tavanı": "Network-view node cap",
    "Graf yüklenmedi.": "The graph is not loaded.",
    "Düğüm": "Nodes",
    "Kenar": "Edges",
    "Yüklenen sembol": "Loaded symbols",
    "Harita çiziliyor": "Rendering network map",
    "Harita hatası": "Network-map error",
    "Graf boş": "The graph is empty",
    "Harita için önce simülasyonu çalıştırın.": "Run a simulation before opening the map.",
    "Başlangıç ifade bağlamı": "Baseline expression context",
    "Yeniden dağılım adayları": "Redistribution candidates",
    "Lokalizasyon verisi yok.": "No localization data are available.",
    "Birincil hedef yok.": "No primary target is available.",
    "Doku ifade grafiği çizilemedi": "The tissue-expression chart could not be rendered",
    "İfade verisi bulunamadı.": "No expression data are available.",
    "Hastalık ara": "Search disease",
    "Hastalık seçin": "Select disease",
    "Hastalık aranıyor": "Searching diseases",
    "Genler getiriliyor": "Retrieving genes",
    "Hastalık bulunamadı": "Disease not found",
    "Hastalık için hedef gen bulunamadı.": "No target genes were found for this disease.",
    "Hiçbir gen seçilemedi.": "No genes could be selected.",
    "ilişkili gen bulundu": "associated genes found",
    "gen hedef olarak seçildi.": "genes selected as targets.",
    "hedef seçili doku/ağ içinde bulunamadı": "target(s) were not found in the selected tissue/network",
    "Hedef veya analiz parametreleri değişti.": "The target or analysis parameters changed.",
    "Önceki keşif sonucu gizlendi; aracı yeniden çalıştırın.": "The previous exploration result is hidden; run the tool again.",
    "Forward pertürbasyon çalıştırılıyor; ağ önemi artışları ölçülüyor": "Running forward perturbation; measuring Network Importance gains",
    "tamamlandı": "complete",
    "hatası": "error",
    "Lütfen hedefi ve doku seçimini kontrol edip yeniden deneyin.": "Check the target and tissue selection, then try again.",
    "Aday ön seçimi": "Candidate preselection",
    "topoloji, topluluk, merkezilik": "topology, communities, and centrality",
    "değerlendiriliyor": "are being evaluated",
    "Filtreyi geçen aday bulunamadı": "No candidates passed the filter",
    "aday mevcut forward simülasyonu ile doğrulanıyor": "candidates are being validated with the current forward simulation",
    "doğrulanmış aday": "validated candidates",
    "Susturma (knockout) senaryosu ağa uygulanıyor": "Applying the edge-attenuation scenario to the network",
    "Enfeksiyon / şok dalgası ağda yayılıyor": "Propagating the modeled network response",
    "ağ önemi + Geçiş Merkeziliği hesabı": "Network Importance + betweenness calculation",
    "Fare modunda ilaçlanabilirlik gate-skoru atlanıyor": "Skipping the druggability gate score in Mouse mode",
    "Stresli/kilitlenen genler sınıflandırıldı, ilaçlanabilirlik skoru hesaplandı": "Stressed/affected genes classified; druggability score calculated",
    "OmniPath yönleri STRING topolojisine uygulanıyor; yönlü motor ayrı çalışıyor": "Applying OmniPath directions to STRING topology; the directed engine runs separately",
    "satırlık rapor derlendi": "row report compiled",
    "rapor hazır": "report ready",
    "diskten yüklendi": "loaded from disk",
    "KEGG ve GO Biological Process yolak analizi otomatik hazırlanıyor": "Preparing KEGG and GO Biological Process pathway analysis",
    "Yolak analizi şu anda tamamlanamadı; simülasyon sonucu korunuyor.": "Pathway analysis could not be completed; the simulation result is retained.",
    "Dokuya duyarlı protein ağı perturbasyon analizi": "Tissue-aware protein-network perturbation analysis",
    "Ağ görselleştirmesi": "Network visualization",
    "Biyolojik bağlam": "Biological Context",
    "Fonksiyonel yorum": "Functional interpretation",
    "Derinlemesine yorum": "Deep interpretation",
    "Detaylı veri ve dışa aktarma": "Detailed data & export",
    "İleri analizler": "Advanced Analysis",
    "Son Simülasyonlar": "Recent simulations",
    "Kaldığın yerden devam etmek için": "To continue where you left off,",
    "aynı hedefi tekrar seç": "select the same target again",
    "Hedef ve ağ bağlamı doğrulandı. Simülasyon henüz çalıştırılmadı.": "Target and network context are validated. The simulation has not run yet.",
    "ÇALIŞMAYA HAZIR": "READY TO RUN",
    "Yapılandır": "Configure",
    "Çalıştır": "Run",
    "İncele": "Review",
    "Ekrandaki seçimler tamamlanmış sonuçla eşleşmiyor.": "The current selections do not match the completed result.",
    "yeni bir analiz çalıştırın.": "Run a new analysis.",
    "Aktif analiz bağlamı": "Active analysis context",
    "Bağlamı uygula": "Apply context",
    "Baskın artış temaları": "Dominant gain themes",
    "Baskın kayıp temaları": "Dominant loss themes",
    "Canonical bileşen kontrolü": "Canonical component check",
    "Aday açıklamaları, anotasyon ve doğrulama önerileri": "Candidate explanations, annotations & validation suggestions",
    "Negatif aday açıklamaları": "Negative candidate explanations",
    "Ağ önemi değişimi alanı olmadığı için aday yorumu üretilemedi.": "Candidate interpretation could not be produced because the Network Importance change field is unavailable.",
    "Mevcut signed sonuçta seçili eşik altında negatif aday yok.": "There are no negative candidates below the selected threshold in the current signed result.",
    "Bu gruba giren aday yok.": "No candidates belong to this group.",
    "İstatistiksel doğrulama bu oturumda çalıştırılmadı.": "Statistical validation was not run in this session.",
    "Mevcut eşiklerde istatistiksel olarak desteklenen aday bulunamadı.": "No statistically supported candidates were found at the current thresholds.",
    "İstatistiksel doğrulama objesinde gösterilebilir alan bulunamadı.": "No displayable fields were found in the statistical-validation object.",
    "GO / KEGG analizi çalıştırılmadı.": "GO / KEGG analysis was not run.",
    "GO / KEGG analizi tamamlanamadı; ağ simülasyonu sonucu korunuyor.": "GO / KEGG analysis could not be completed; the network-simulation result is retained.",
    "GO / KEGG analizinde gösterilecek sonuç bulunamadı.": "No GO / KEGG results are available to display.",
    "Ham rapor verisi bulunamadı.": "Raw report data are unavailable.",
    "Tam veri tablosunu aç": "Open full data table",
    "Tam matris, sütunlar ve dışa aktarma": "Full matrix, columns & export",
    "Seçili genin ayrıntıları": "Selected gene details",
    "Seçili kaybın ayrıntıları": "Selected loss details",
    "Seçili yanıtın ayrıntıları": "Selected response details",
    "Kaynak ağ önemi kaybı tablosu ve dışa aktarma": "Source Network Importance-loss table & export",
    "Kaynak yeniden dağılım tablosu ve dışa aktarma": "Source redistribution table & export",
    "Bu simülasyonda gösterilecek ağ yanıtı kaydı bulunamadı.": "No network-response records are available to display for this simulation.",
    "Doz-yanıt": "Dose response",
    "Şiddet hassasiyeti": "Severity sensitivity",
    "Yayılım izi": "Propagation trace",
    "Dokular arası": "Across tissues",
    "Doku karşılaştırmasını başlat": "Start tissue comparison",
    "Doz-yanıt simülasyonunu başlat": "Start dose-response simulation",
    "Doz-yanıt analizi bu koşulda tamamlanamadı.": "Dose-response analysis could not be completed in this context.",
    "Threshold Sweep fare motorunda desteklenmiyor.": "Threshold Sweep is not supported by the Mouse engine.",
    "Ağ eşikleri taranıyor": "Scanning network thresholds",
    "Etkinin yayılımını incele": "Inspect propagation of the effect",
    "Şiddet hassasiyetini çalıştır": "Run severity sensitivity",
    "Çoklu hedef etkileşimini doğrula": "Validate multi-target interaction",
    "Metodoloji ve yeniden üretilebilirlik metadata'sı": "Methodology & reproducibility metadata",
    "İleri bilimsel doğrulama": "Advanced scientific validation",
    "Ağ haritası ayarları": "Network-map settings",
    "Gelişmiş simülasyon ayarları": "Advanced simulation settings",
    "Geliştirici modu": "Developer mode",
    "Dosya durumu": "File status",
    "Simülasyon geçmişi": "Simulation history",
    "Bu oturumda kayıtlı analiz yok.": "There is no saved analysis in this session.",
    "Unified Araştırma Raporu": "Unified Research Report",
    "Sağlam bulgular": "Robust findings",
    "Yön duyarlı": "Direction-sensitive",
    "Motor farkları": "Engine differences",
    "Kanıt ve teknik ayrıntılar": "Evidence & technical details",
    "Ham motor sonuçları": "Raw engine results",
    "Makine tarafından okunabilir provenance": "Machine-readable provenance",
    "Rotalar ve kanıt": "Routes & evidence",
    "Simülasyon sonucuna dön": "Return to simulation result",
    "Kritik gen ayrıntıları": "Critical-gene details",
    "Analize dön": "Return to analysis",
    "İkincil ağ bağlamı ve kanıt": "Secondary network context & evidence",
    "Ölçülen ağ önemi artışına dayalı kompanzasyon adayı bulunamadı.": "No compensation candidate based on a measured Network Importance gain was found.",
    "Aktif doku ağında seçilen kanıt filtresini geçen aday bulunamadı.": "No candidate passed the selected evidence filter in the active tissue network.",
    "öngörülen hedef stresi": "predicted target stress",
    "Ayrıntılı çıktı özeti": "Detailed output summary",
    "Kararlı sonuç ölçümleri": "Stable result measures",
    "Yanıt dengesi": "Response balance",
    "Ağ önemi artanlar": "Network Importance gains",
    "Ağ önemi azalanlar": "Network Importance losses",
    "Bu sonuçta pozitif yeniden dağılım adayı yok.": "There are no positive redistribution candidates in this result.",
    "Bu sonuçta negatif yeniden dağılım adayı yok.": "There are no negative redistribution candidates in this result.",
    "Ağ yanıtı": "Network Response",
    "Global verimlilik değişimi": "Global efficiency change",
    "etkilenmiş kayıt": "affected records",
    "Öne çıkan bulgu": "Key finding",
    "Biyolojik vurgu": "Biological highlight",
    "Mevcut zenginleştirme sonuçlarında ilk kayıt.": "First record in the current enrichment results.",
    "Mevcut biyolojik bağlam": "Current biological context",
    "Bu sonuç için kayıtlı zenginleştirme sonucu bulunmuyor.": "No recorded enrichment result is available for this outcome.",
    "Önemli bağlam": "Important context",
    "Sonuç sınırı": "Result boundary",
    "Ağ yeniden dağılımı biyolojik nedensellik veya tedavi önerisi değildir.": "Network redistribution is not biological causality or a treatment recommendation.",
    "Nasıl yorumlanır?": "How should this be interpreted?",
    "Mavi elmas = pertürbasyon hedefi": "Blue diamond = perturbation target",
    "Yeşil = yeniden-dağılım adayı": "Green = redistribution candidate",
    "Gri = ağ bağlamı": "Gray = network context",
    "Sarı = 2D köprü düğümü": "Yellow = 2D bridge node",
    "Harita Modu": "Map mode",
    "Sadece İlgili Genler (Hızlı)": "Relevant genes only (fast)",
    "Gerçek Ağ — 2B": "Real Network — 2D",
    "Gerçek Ağ — 3B": "Real Network — 3D",
    "Tüm çekirdek genlere etiket göster": "Show labels for all core genes",
    "Başlangıç doku ifadesi": "Baseline tissue expression",
    "anotasyon bağlamıdır": "is annotation context",
    "pertürbasyon sonucu": "perturbation result",
    "Lokalizasyon": "Localization",
    "Gerçek Ağ": "Real Network",
    "Biyolojik Bağlam": "Biological Context",
    "Kanıt & Kaynaklar": "Evidence & sources",
    "Ham Veri & İndirme": "Raw data & download",
    "İleri Araçlar": "Advanced tools",
    "Sonucu Anla": "Understand the result",
    "Ağı Keşfet": "Explore the network",
    "Kanıtı Doğrula": "Validate evidence",
    "Araştırma Gezgini": "Research Explorer",
    "Genel görünüm": "Overview",
    "İlişkiler": "Relationships",
    "Araştırma bölümü": "Research section",
    "Tüm araştırma çıktılarını indir": "Download all Research outputs",
    "Tam araştırma dosyasını hazırla": "Prepare complete Research export",
    "Tüm araştırma tabloları dışa aktarılıyor": "Exporting all Research tables",
    "Tam dışa aktarım yalnızca istendiğinde hazırlanır": "The complete export is prepared only on request",
    "Threshold Sweep tamamlandı.": "Threshold Sweep complete.",
    "Fare modunda Threshold Sweep henüz desteklenmiyor.": "Threshold Sweep is not yet supported in Mouse mode.",
    "Bu bölgede yaklaşık": "This region will target approximately",
    "gen hedeflenecek.": "genes.",
    "Dosya": "File",
    "Graf": "Graph",
    "Session": "Session",
    "CSV Zorla Yükle": "Force-load CSV",
    "Okunamadı.": "Could not be read.",
    "GC Çalıştır": "Run GC",
    "Aynı Classic / Directed / Evidence çağrısı kullanılır": "The same Classic / Directed / Evidence call is used",
    "yalnızca eylem sayfa içine taşındı.": "only the action has moved into the page.",
    "Kompanzasyon Adaylarını Bul": "Find compensation candidates",
    "Sonuçlar deneysel kanıt değil, hesaplamalı ağ tahminidir.": "Results are computational network predictions, not experimental evidence.",
    "Bu tablo sunum amaçlıdır; hesaplama parametrelerini değiştirmez.": "This table is presentation-only; it does not change calculation parameters.",
    "CSV formatı hatalı. Sütunlar:": "CSV format is invalid. Columns:",
    "Ham CSV": "Raw CSV",
    "Doz–yanıt, şiddet, yayılım ve doku araçları Classic modeline aittir.": "Dose-response, severity, propagation, and tissue tools belong to the Classic model.",
    "Bu araçlar için Classic analizi seçin.": "Select Classic analysis for these tools.",
    "3B görünüm için": "For the 3D view,",
    "2B ağ görünümü için": "For the 2D network view,",
    "kurulu değil.": "is not installed.",
    "Grafta eşleşen düğüm yok.": "No matching nodes are present in the graph.",
    "Graf boş — seçilen doku için düğüm bulunamadı.": "The graph is empty—no nodes were found for the selected tissue.",
    "Bu gen için doku ifade verisi bulunamadı.": "No tissue-expression data are available for this gene.",
    "Başlangıç ifade bağlamı için pertürbasyon hedefi bulunamadı.": "No perturbation target is available for baseline-expression context.",
    "Hücresel dağılım bağlamı için yeniden-dağılım adayı bulunamadı.": "No redistribution candidate is available for cellular-distribution context.",
    "Stresli gen yok.": "There are no stressed genes.",
    "İleri teknik analizler · Doz-yanıt ve eşik taraması": "Advanced technical analyses · dose response & threshold sweep",
    "Ağ Direnci ve LCC Oranı": "Network resilience & LCC ratio",
    "Görüntülenecek eşik taraması verisi yok.": "There are no threshold-sweep data to display.",
    "Önce bir simülasyon çalıştırın; KEGG ve GO sonuçları simülasyonla birlikte otomatik hazırlanır.": "Run a simulation first; KEGG and GO results are prepared automatically with the simulation.",
    "Yolak analizini yeniden dene": "Retry pathway analysis",
    "Ek biyolojik yorum ve anotasyon ayrıntıları": "Additional biological interpretation & annotation details",
    "Bu eski sonuç biçimi için araştırma bağlamı kullanılamıyor; ham sonuçlar erişilebilir durumda.": "Research Context is unavailable for this legacy result format; raw results remain accessible.",
    "Aktif analiz sonucu değiştiği için araştırma bağlamı yenilendi.": "Research Context was refreshed because the active analysis result changed.",
    "Sembol çevrilemedi.": "The symbol could not be resolved.",
    "Bir veya daha fazla gen seçin": "Select one or more genes",
    "Varsayılanları Yükle": "Restore defaults",
    "Eşik taramasını başlat": "Start threshold sweep",
    "Hard Reset tamamlandı": "Hard Reset complete",
    "Hedef türü": "Target type",
    "Gen Adı Ara": "Search gene name",
    "Hastalık Seç": "Select disease",
    "Manuel Lokalizasyon": "Manual localization",
    "Etki modu": "Effect mode",
    "Ağ-Aracılı Etki": "Network-mediated effect",
    "Doğrudan Etki": "Direct effect",
    "Birleşik": "Combined",
    "Aday limiti": "Candidate limit",
    "Doku": "Tissue",
    "Organizma": "Organism",
    "Hedef": "Target",
    "Çalışma alanı": "Workspace",
    "Pertürbasyon": "Perturbation",
    "Bir hedef seçin": "Choose a target",
    "Hedef gen": "Target gene",
    "Sonuçları okuma rotası": "Result reading route",
    "Üç ana görev, aynı hesaplanmış sonucun farklı inceleme derinlikleridir.": "Three tasks provide different levels of examination for the same computed result.",
    "Başlangıç noktası": "Starting point",
    "Yanıtın büyüklüğünü, yön dengesini ve en önemli bulguları okuyun.": "Review the response magnitude, directional balance, and key findings.",
    "Keşif": "Exploration",
    "Önce aday ve ağ yanıtını, ardından bu kayıtların biyolojik bağlamını inceleyin.": "Review candidates and the network response first, then inspect their biological context.",
    "Doğrulama": "Validation",
    "Yorumdan ham kaynağa ilerleyin; dışa aktarma ve ileri araçlar burada bulunur.": "Move from interpretation to recorded sources; exports and advanced tools are available here.",
    "Aday gezgini": "Candidate explorer",
    "Seçili adayın kayıtlı ayrıntıları": "Recorded details for the selected candidate",
    "İncelenecek kayıt": "Record to inspect",
    "Hesaplanan yanıt": "Computed response",
    "Kanıt ve kaynak": "Evidence and sources",
    "Göreli ağ önemi değişimi; ekspresyon, aktivasyon veya biyolojik işlev ölçümü değildir.": "Relative network-importance change; it is not a measure of expression, activation, or biological function.",
    "Bu adayı içeren zenginleştirme kayıtlarını göster": "Show enrichment records containing this candidate",
    "Bu aday için mevcut zenginleştirme tablosunda eşleşen üyelik yok.": "No matching membership for this candidate is present in the available enrichment table.",
    "Eksik kayıt, ilişkinin yokluğuna kanıt değildir. Anotasyon bir pertürbasyon sonucu değildir.": "A missing record is not evidence that a relationship is absent. Annotation is not a perturbation result.",
    "Tüm kaynak alanlarını göster": "Show all recorded fields",
    "Sayfa": "Page",
    "Dışa aktarma formatı": "Export format",
    "indir": "download",
    "satır gösteriliyor.": "rows shown.",
    "Satırlar": "Rows",
    "sayfa": "page",
    "Sinyalin ağda ne kadar yayılacağını belirler. Yüksek değer = daha global etki.": "Controls how far the signal propagates through the network. Higher values produce a more global effect.",
    "Susturma sonrası kalan kenar ağırlığı. 0.0001 = çok güçlü susturma, 0.1 = daha hafif/kısmi inhibisyon.": "Remaining edge weight after attenuation. 0.0001 = very strong attenuation; 0.1 = milder or partial inhibition.",
    "Doz-yanıt eğrisinin dikliğini kontrol eder.": "Controls the steepness of the dose-response curve.",
    "Hedef inhibe oldukça paralog genlerin aktivitesini artırma yüzdesi.": "Percentage used to increase paralog-gene activity as the target is inhibited.",
    "Hızlı/Dengeli modlar sabit tohumlu kaynak örneklemesi kullanır. Tam mod, nihai raporlar için tüm düğümlerle hesaplar.": "Fast and Balanced modes use fixed-seed source sampling. Full mode calculates with all nodes for final reports.",
    "CSI Ağ Haritası'nda 'Gerçek Ağ' modu seçildiğinde tarayıcıya gönderilecek en fazla düğüm sayısı. Kilitlenen ve stresli genler bu tavandan bağımsız olarak HER ZAMAN dahil edilir; tavan yalnızca eklenecek bağlam (komşu/hub) düğümlerini sınırlar. Daha düşük değer daha okunaklı, daha yüksek değer daha kapsamlı ama daha yoğun bir harita üretir.": "Maximum number of nodes sent to the browser when Real Network mode is selected in the CSI Network Map. Bottleneck and stressed genes are always included independently of this cap; it limits only added context nodes such as neighbours and hubs. Lower values are more readable; higher values are more comprehensive but denser.",
    "Yalnızca bu kadar en yüksek skorlu kilitlenen/stresli gene metin etiketi basılır; geri kalanlar üzerine gelince (hover) görünür. Bu, yüzlerce üst üste yazının okunamaz bir yığın oluşturmasını önler.": "Text labels are shown only for this many highest-scoring bottleneck or stressed genes; the remainder appear on hover. This prevents an unreadable overlap of hundreds of labels.",
    "🧭 Parametre Kılavuzu (Nasıl Kullanılır?)": "🧭 Parameter guide (how to use it)",
    "Ağ önemi yayılımı (α)": "Network-importance propagation (α)",
    "Sinyalin ağda ne kadar uzağa yayılacağını belirler.": "Controls how far the signal propagates through the network.",
    "0.85 (Varsayılan):": "0.85 (Default):",
    "Standart davranış.": "Standard behaviour.",
    "Sinyal tüm ağa yayılır, global etkileri görmek için idealdir.": "The signal spreads across the network, showing global effects.",
    "Sinyal hedef gene yakın kalır, sadece yerel komşuların stresini test etmek için kullanılır.": "The signal remains near the target gene and is used to inspect stress in local neighbours.",
    "Susturma Şiddeti": "Attenuation strength",
    "Hedef genin bağlantılarının ne kadar zayıflatılacağını belirler.": "Controls how strongly the target gene's connections are attenuated.",
    "Başlangıç kenar ağırlığının %0.1’i kalır; deneysel knockout değildir.": "0.1% of the initial edge weight remains; this is not an experimental knockout.",
    "Kısmi inhibisyon (ilaç etkisi), doz-yanıt testleri için uygundur.": "Partial inhibition, suitable for dose-response tests.",
    "Başlangıç kenar ağırlığının %10’u kalır; biyolojik aktivite ölçümü değildir.": "10% of the initial edge weight remains; this is not a measure of biological activity.",
    "Hill Katsayısı (n)": "Hill coefficient (n)",
    "Klasik sigmoid eğri, çoğu biyolojik sistem için uygundur.": "Classic sigmoid curve for the model.",
    "Daha yumuşak, kademeli etki (ilaç etkisi yavaş başlar).": "Softer, gradual effect (drug effect begins more slowly).",
    "Çok dik eğri (aşırı hassas sistemler veya işbirlikçi bağlanma).": "Very steep curve (highly sensitive systems or cooperative binding).",
    "Hedef inhibe olduğunda, benzer işlevli yedek genlerin aktivitesini ne kadar artıracağını simüle eder.": "Simulates how much to increase activity of backup genes with similar functions when the target is inhibited.",
    "%10 (Varsayılan):": "%10 (Default):",
    "Ilımlı bir telafi mekanizması.": "Moderate compensation in the model.",
    "Modelde paralog katkısının artırılmadığı senaryo.": "Scenario with no increased paralog contribution in the model.",
    "Modelde daha yüksek paralog katkısı; ilaç direncini kanıtlamaz.": "Higher paralog contribution in the model; it does not establish drug resistance.",
    "Fare modunda ilaçlanabilirlik gate-skoru atlanıyor (yapısal veri yok).": "Skipping the druggability gate score in Mouse mode because structural data are unavailable.",
    "Stresli/kilitlenen genler sınıflandırıldı, ilaçlanabilirlik skoru hesaplandı.": "Stressed and bottleneck genes classified; druggability score calculated.",
    "OmniPath yönleri STRING topolojisine uygulanıyor; yönlü motor ayrı çalışıyor...": "Applying OmniPath directions to STRING topology; the directed engine runs separately...",
    "satırlık rapor derlendi.": "row report compiled.",
    "satır rapor hazır.": "row report ready.",
    "Diskten": "Loaded from disk:",
    "satır yüklendi.": "rows loaded.",
}

# Legacy presentation literals retained by Turkish-mode screens.
EN_REPLACEMENTS.update({
    "Fare motoru (mouse_main.py) yüklenemediği için Fare modu kullanılamıyor.": "Mouse mode is unavailable because the Mouse engine (mouse_main.py) could not be loaded.",
    "CSV okuma hatası": "CSV read error",
    "Excel dışa aktarma başarısız; CSV oluşturuldu.": "Excel export failed; a CSV was created.",
    "Open Targets API GraphQL hatası": "Open Targets API GraphQL error",
    "Open Targets API zaman aşımına uğradı. Lütfen tekrar deneyin.": "The Open Targets API timed out. Please try again.",
    "Open Targets API'ye bağlanılamadı. İnternet bağlantınızı kontrol edin.": "Could not connect to the Open Targets API. Check your internet connection.",
    "API HTTP hatası": "API HTTP error",
    "Open Targets API beklenmeyen (JSON olmayan) bir yanıt döndürdü.": "The Open Targets API returned an unexpected non-JSON response.",
    "Bu EFO ID için hastalık verisi bulunamadı.": "No disease data were found for this EFO ID.",
    "mouse_config.MOUSE_SYMBOL_MAP boş ya da bulunamadı.": "mouse_config.MOUSE_SYMBOL_MAP is empty or unavailable.",
    "ensp_with_symbols.csv bulunamadı.": "ensp_with_symbols.csv was not found.",
    "Hastalık Seç": "Select disease",
    "Örn:": "Example:",
    "ilişkili gen bulundu": "associated genes found",
    "sembol ENSP'ye çevrilemedi": "symbols could not be resolved to ENSP identifiers",
    "gen hedef olarak seçildi.": "genes selected as target.",
    "Bu hastalık için hedef gen bulunamadı.": "No target gene was found for this disease.",
    "Hastalık bulunamadı ya da API'den sonuç dönmedi (üstteki hata mesajına bakın).": "The disease was not found or the API returned no result; see the error message above.",
    "Simülasyon Geçmişi (son 10)": "Simulation history (last 10)",
    "Target Stress Search nasıl okunur?": "How to read Target Stress Search",
    "Eşik taramasını başlat": "Start threshold sweep",
    "Çalışma alanını nasıl kullanırım?": "How do I use this workspace?",
    "Seçimler değişti": "Selections changed",
    "Mevcut sonuç eski bağlama ait olduğu için gizlendi.": "The current result was hidden because it belongs to an earlier context.",
    "Yeni analizi çalıştır": "Run new analysis",
    "Threshold Sweep çalışıyor...": "Threshold Sweep running...",
    "Threshold Sweep tamamlandı.": "Threshold Sweep complete.",
    "Fare modunda Threshold Sweep henüz desteklenmiyor.": "Threshold Sweep is not yet supported in Mouse mode.",
    "Hedef genler": "Target genes",
    "veri tablosunda bulunamadı.": "were not found in the data table.",
    "CSV Zorla Yükle": "Force-load CSV",
    "Okunamadı.": "Could not be read.",
    "GC Çalıştır": "Run GC",
    "Nasıl çalışır?": "How does it work?",
    "Bir hedef gen seçin": "Select a target gene",
    "Mod seçimine dön": "Return to mode selection",
    "Son Simülasyonlar": "Recent simulations",
    "Kaldığın yerden devam etmek için sol menüden aynı hedefi tekrar seç": "To continue where you left off, select the same target again in the side menu.",
    "Veri formatı beklenmeyen tipte.": "The data format has an unexpected type.",
    "Bu tablo sunum amaçlıdır; hesaplama parametrelerini değiştirmez.": "This table is for presentation only; it does not change calculation parameters.",
    "Ayrıntılı çıktı özeti": "Detailed output summary",
    "Yanıt dengesi": "Response balance",
    "Pozitif ve negatif ağ yanıtları birlikte gösterilir. Ağ yanıtının işareti, biyolojik aktivasyon/baskılama anlamına gelmez.": "Positive and negative network responses are displayed together. The response sign does not mean biological activation or inhibition.",
    "Tüm pozitif ve negatif kayıtlar": "All positive and negative records",
    "Öne çıkan bulgu": "Key finding",
    "Mevcut zenginleştirme sonuçlarında ilk kayıt.": "First record in the current enrichment results.",
    "Bu sonuç için kayıtlı zenginleştirme sonucu bulunmuyor.": "No recorded enrichment result is available for this outcome.",
    "Önemli bağlam": "Important context",
    "Nasıl yorumlanır?": "How should this be interpreted?",
    "Doz–yanıt, şiddet, yayılım ve doku araçları Classic modeline aittir. Bu araçlar için Classic analizi seçin.": "Dose-response, severity, propagation, and tissue tools belong to the Classic model. Select Classic analysis to use these tools.",
    "Harita çiziliyor...": "Rendering network map...",
    "Grafta eşleşen düğüm yok.": "No matching node is present in the graph.",
    "Graf boş — seçilen doku için düğüm bulunamadı.": "The graph is empty; no nodes were found for the selected tissue.",
    "Harita için önce simülasyonu çalıştırın.": "Run a simulation before opening the map.",
    "Bu gen için doku ifade verisi bulunamadı.": "No tissue-expression data were found for this gene.",
    "Başlangıç ifade bağlamı için pertürbasyon hedefi bulunamadı.": "No perturbation target was found for the baseline expression context.",
    "Biyolojik yorumlama bu rapor için görüntülenemedi; hesaplanmış ağ sonuçları korunuyor.": "Biological interpretation could not be displayed for this report; computed network results are retained.",
    "İleri teknik analizler · Doz-yanıt ve eşik taraması": "Advanced technical analyses · dose response and threshold sweep",
    "Ağ Direnci ve LCC Oranı": "Network resilience and LCC ratio",
    "Görüntülenecek eşik taraması verisi yok.": "No threshold-sweep data are available to display.",
    "Önce bir simülasyon çalıştırın; KEGG ve GO sonuçları simülasyonla birlikte otomatik hazırlanır.": "Run a simulation first; KEGG and GO results are prepared automatically with the simulation.",
    "Yolak analizini yeniden dene": "Retry pathway analysis",
    "Ek biyolojik yorum ve anotasyon ayrıntıları": "Additional biological interpretation and annotation details",
    "Sophiark nasıl kullanılır?": "How do I use Sophiark?",
    "Sonuçları nasıl okumalıyım?": "How should I read the results?",
    "Aktif analiz bağlamı": "Active analysis context",
    "Tür": "Species",
    "Bağlamı uygula": "Apply context",
    "Doz–yanıt işlemi tamamlanamadı. Ayrıntılar yerel iş günlüğünde.": "Dose-response processing could not be completed. Details are in the local log.",
    "Bu doz–yanıt çalışmasını durdur": "Stop this dose-response run",
    "Mevcut hesaplama çalıştırılıyor…": "The current calculation is running…",
    "Bu analiz tamamlanamadı. Ana sonuç korunuyor; teknik ayrıntılar yerel günlükte.": "This analysis could not be completed. The main result is retained; technical details are in the local log.",
    "Bu aracın parametreleri değişti; önceki sonuç gizlendi. Yeniden çalıştırın.": "This tool's parameters changed; the earlier result is hidden. Run it again.",
    "Doz–yanıt": "Dose response",
    "Şiddet hassasiyeti": "Severity sensitivity",
    "Yayılım izi": "Propagation trace",
    "Dokular arası": "Across tissues",
    "Farklı kalan aktivite değerlerinde ağ nasıl yanıt verir?": "How does the network respond at different remaining activity values?",
    "Bulgular pertürbasyon şiddetine ne kadar duyarlı?": "How sensitive are the findings to perturbation strength?",
    "Etki hangi ağ rotalarında izlenebilir?": "Along which network routes can the effect be traced?",
    "Aynı hedef farklı dokularda nasıl yanıt verir?": "How does the same target respond across tissues?",
    "Karşılaştırılacak dokular": "Tissues to compare",
    "Gelişmiş simülasyon ayarları": "Advanced simulation settings",
    "Ağ haritası ayarları": "Network-map settings",
    "İleri bilimsel doğrulama": "Advanced scientific validation",
    "Geliştirici modu": "Developer mode",
    "Simülasyon geçmişi": "Simulation history",
    "Karşılaştırma": "Comparison",
    "Analiz geçmişi": "Analysis history",
    "Geçmiş indeksini yeniden oluştur": "Rebuild history index",
    "Geçmiş analiz": "Historical analysis",
    "Bir kayıt seçin": "Select a record",
    "Henüz kalıcı Unified analiz bundle’ı yok.": "There is no persistent Unified analysis bundle yet.",
    "Modeller arası bulgular ve kayıtlı analizler": "Cross-model findings and saved analyses",
    "Rapor görünümü": "Report view",
    "Kayıtlı analizler": "Saved analyses",
    "Unified analizi başlat": "Start Unified analysis",
    "Classic ve Directed hesaplanıyor…": "Classic and Directed are being calculated…",
    "Ağ Yanıtı": "Network Response",
    "Biyolojik Bağlam": "Biological Context",
    "Bu sonuçta incelenecek aday yok.": "There are no candidates to inspect in this result.",
    "Bu sonuçta aday kimliği bulunmuyor; tüm değerlere tam tablodan ulaşabilirsiniz.": "Candidate identity is unavailable in this result; all values remain available in the full table.",
    "Önce yanıt büyüklüğünü ve başlangıç bağlamını tarayın; yalnız gerekirse kayıt ayrıntısını açın.": "First review response magnitude and baseline context; open recorded details only when needed.",
    "İlk 10": "First 10",
    "aday": "candidates",
    "Tam sonuç aşağıdaki ağ yanıtında": "The full result is retained in the Network Response below",
    "Tüm araştırma çıktıları için format": "Format for all Research outputs",
    "Bu format hazırlanamadı; CSV paketi seçerek yeniden deneyin.": "This format could not be prepared; select the CSV package and try again.",
    "Excel oluşturulamadı; CSV indirilebilir durumda.": "Excel could not be created; CSV remains available for download.",
    "Düğüm ayrıntıları": "Node details",
    "Rotalar ve kanıt": "Routes and evidence",
    "Yönlü kanıt": "Directed evidence",
    "Simülasyon sonucuna dön": "Return to simulation result",
})


def localize_text(value):
    """Translate a presentation string only when the active UI is English."""
    if isinstance(value, list):
        return [localize_text(item) for item in value]
    if isinstance(value, tuple):
        return tuple(localize_text(item) for item in value)
    if locale() != "en" or not isinstance(value, str):
        return value
    translated = value
    for source, target in sorted(EN_REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        translated = translated.replace(source, target)
    return translated


def install_streamlit_localization() -> None:
    """Apply the central presentation translator to Streamlit output surfaces.

    This covers legacy literals in root and component renderers without
    changing calculation inputs or option values. It is idempotent.
    """
    try:
        from streamlit.delta_generator import DeltaGenerator
    except Exception:
        return
    if getattr(DeltaGenerator, "_sophiark_locale_installed", False):
        return

    def wrap(method):
        original = getattr(DeltaGenerator, method, None)
        if original is None:
            return
        @wraps(original)
        def localized(self, *args, **kwargs):
            if args:
                args = (localize_text(args[0]), *args[1:])
            else:
                for name in ("body", "label", "text"):
                    if name in kwargs:
                        kwargs[name] = localize_text(kwargs[name])
                        break
            return original(self, *args, **kwargs)
        setattr(DeltaGenerator, method, localized)

    names = (
        "markdown", "caption", "info", "warning", "error", "success", "write",
        "button", "download_button", "checkbox", "toggle", "radio", "selectbox",
        "multiselect", "select_slider", "segmented_control", "text_input", "number_input",
        "slider", "expander", "tabs", "title", "header", "subheader", "status",
        "spinner", "metric", "toast",
    )
    for name in names:
        wrap(name)
    # The module-level ``st.*`` convenience methods can be pre-bound in some
    # Streamlit versions, so wrap them too. Container methods are covered by
    # DeltaGenerator above.
    for name in names:
        original = getattr(st, name, None)
        if original is None:
            continue
        @wraps(original)
        def localized_global(*args, _original=original, **kwargs):
            if args:
                args = (localize_text(args[0]), *args[1:])
            else:
                for field in ("body", "label", "text"):
                    if field in kwargs:
                        kwargs[field] = localize_text(kwargs[field])
                        break
            return _original(*args, **kwargs)
        setattr(st, name, localized_global)
    column_config = getattr(st, "column_config", None)
    if column_config is not None:
        for name in ("TextColumn", "NumberColumn", "CheckboxColumn", "SelectboxColumn", "LinkColumn", "ProgressColumn", "DateColumn"):
            original = getattr(column_config, name, None)
            if original is None:
                continue
            @wraps(original)
            def localized_column(*args, _original=original, **kwargs):
                if args:
                    args = (localize_text(args[0]), *args[1:])
                elif "label" in kwargs:
                    kwargs["label"] = localize_text(kwargs["label"])
                if "help" in kwargs:
                    kwargs["help"] = localize_text(kwargs["help"])
                return _original(*args, **kwargs)
            setattr(column_config, name, localized_column)
    DeltaGenerator._sophiark_locale_installed = True


def locale() -> str:
    return str(st.session_state.get("ui_locale", "en")).lower()


def t(key: str) -> str:
    return STRINGS.get(locale(), STRINGS["en"]).get(key, STRINGS["en"].get(key, key))
